config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = 'Store'
admin.site.index_title = 'Special Access'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('accounts/', include('allauth.urls')),
    path('rosetta/', include('rosetta.urls')),

    path('store/', include('store.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('home/', views.HomePageView.as_view(), name='home'),
    path('category_list/', views.CategoryListView.as_view(), name='category_list'),
    path('product_list/', views.ProductListView.as_view(), name='product_list'),
    path('product_detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('comments/<int:pk>/', views.CommentCreateView.as_view(), name='comment_create'),
    path('cart_detail/', views.cart_detail_view, name='cart_detail'),
    path('cart_add/<int:pk>/', views.add_to_cart_view, name='cart_add'),
    path('cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart_remove/<int:pk>/<uuid:product_version_id>/', views.cart_remove, name='cart_remove'),
    path('order_create/', views.order_create_view, name='order_create'),
    path('payment_process/', views.payment_process, name='payment_process'),
    path('payment_callback/', views.payment_callback, name='payment_callback'),
]

store/forms.py
from django.forms.models import ModelForm
from .models import ProductComment, Category, Color, Product, Order
from django import forms

from .serializers import SizeSerializer, ColorSerializer


class CommentForm(ModelForm):
    class Meta:
        model = ProductComment
        fields = ['body', 'product_stars']



class ProductSearchForm(forms.Form):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False, label='دسته بندی')
    color = forms.ModelChoiceField(queryset=Color.objects.all(), required=False, label='رنگ')
    min_price = forms.IntegerField(required=False, label='حداقل قیمت')
    max_price = forms.IntegerField(required=False, label='حداکثر قیمت')
    available = forms.BooleanField(required=False, label='موجود بودن')


class AddToCartForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1,31)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)
    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)


class SelectSizeAndColorForm(forms.Form):
    size = forms.ChoiceField(choices=[], label='Select Size')
    color = forms.ChoiceField(choices=[], label='Select Color')

    def __init__(self, *args, **kwargs):
        product_sizes = kwargs.pop('product_sizes', [])
        product_colors = kwargs.pop('product_colors', [])
        super(SelectSizeAndColorForm, self).__init__(*args, **kwargs)

        size_choices = SizeSerializer(product_sizes, many=True).data
        color_choices = ColorSerializer(product_colors, many=True).data

        self.fields['size'].choices = [(size['id'], size['title']) for size in size_choices]
        self.fields['color'].choices = [(color['id'], color['fa_name']) for color in color_choices]


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'address', 'post_code', 'order_note']

        widgets = {
            'address': forms.Textarea(attrs={'rows': 3}),
            'order_note': forms.Textarea(attrs={'rows': 5, 'placeholder': 'if you have any note please write here '})
        }

store/views.py
import json
from cmath import inf

import requests
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.serializers import serialize
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView, TemplateView

from django.shortcuts import render
from django.views.generic import ListView

from django.views.generic import ListView

from config import settings
from .cart import Cart
from .models import Product, Category, Color, ProductPricing, Size, Order, OrderItem

from .forms import CommentForm, ProductSearchForm, AddToCartForm, SelectSizeAndColorForm, OrderForm
from .models import Product, Category, ProductComment, Variant, Image, Tag, Color, AttributeValue, ProductPricing

from colorama import init, Fore, Back, Style

class HomePageView(TemplateView):
    template_name = 'store/home.html'


class CategoryListView(ListView):
    template_name = 'store/category_list.html'
    context_object_name = 'categories'
    queryset = Category.objects.all()


class ProductListView(ListView):
    model = Product
    template_name = 'store/product_list.html'
    context_object_name = 'products'
    paginate_by = 10
    form_class = ProductSearchForm

    def get_queryset(self):
        queryset = super().get_queryset().select_related('category', 'brand').prefetch_related('colors', 'attribute',
                                                                                               'tags', 'price').all()

        category = self.request.GET.get('category')
        color = self.request.GET.get('color')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')
        reset_filters = self.request.GET.get('reset')
        available = self.request.GET.get('available')

        if category:
            queryset = queryset.filter(category__fa_name=category)
        if color:
            queryset = queryset.filter(colors__en_name=color)
        # اضافه کردن شرط‌ها فقط اگر reset فراخوانی نشده باشد
        if not reset_filters:
            if min_price:
                queryset = queryset.filter(price__price__gte=min_price)
            if max_price:
                queryset = queryset.filter(price__price__lte=max_price)
        elif reset_filters:
            queryset = Product.objects.all()
        # محاسبه موجودی محصول بر اساس مجموع موجودی واریانت‌ها
        queryset = queryset.annotate(total_inventory=Sum('variant__inventory'))

        if available:
            queryset = queryset.filter(total_inventory__gt=0)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class(self.request.GET)
        context['categories'] = Category.objects.prefetch_related('children', 'products').all()
        context['colors'] = Color.objects.prefetch_related('products').all()
        context['tags'] = Tag.objects.all()
        cart = Cart(self.request)
        context['cart'] = cart

        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'store/product_detail.html'
    context_object_name = 'product'

    def get_queryset(self):
        return Product.objects.select_related('category__parent').prefetch_related('price', 'images', 'attribute',
                                                                                   'attribute__category',
                                                                                   'attribute_values', 'price__color',
                                                                                   'variant__size', 'comments__user', )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['add_to_cart_form'] = AddToCartForm()
        context['select_size_and_color_form'] = SelectSizeAndColorForm(product_sizes=self.object.sizes.all(), product_colors=self.object.colors.all())

        context['comment_form'] = CommentForm()
        context['product_images'] = self.object.images.all()
        context['attribute_values'] = AttributeValue.objects.select_related('attribute').filter(product_id=self.object.id)
        context['variants'] = Variant.objects.select_related('size').filter(product_id=self.object.id).all()
        related_products = Product.objects.select_related('category__parent').prefetch_related('price__color').filter(
            category=self.object.category).exclude(id=self.object.id)[:6]
        context['related_products'] = related_products
        cart = Cart(self.request)
        context['cart'] = cart


        return context

def cart_detail_view(request):
    cart = Cart(request)

    for item in cart:
        item['product_update_quantity_form'] = AddToCartForm(initial={
            'quantity': item['quantity'],
            'inplace': True,
        })

        item['product_color_and_size_form'] = SelectSizeAndColorForm(initial={
            'color': item['color_id'],
            'size': item['size_id'],
        })

    return render(request, 'store/cart_detail.html', {'cart': cart,})


@require_POST
def add_to_cart_view(request, pk):
    cart = Cart(request)

    product = Product.objects.get(id=pk)
    price = ProductPricing.objects.get(product_id=pk)
    add_to_cart_form = AddToCartForm(request.POST)

    if add_to_cart_form.is_valid():
        add_to_cart_cleaned_data = add_to_cart_form.cleaned_data
        quantity = add_to_cart_cleaned_data['quantity']
        inplace = add_to_cart_cleaned_data['inplace']

        color_and_size_form = SelectSizeAndColorForm(request.POST, product_sizes=product.sizes.all(), product_colors=product.colors.all())
        if color_and_size_form.is_valid():
            color_and_size_cleaned_data = color_and_size_form.cleaned_data
            color_id = color_and_size_cleaned_data['color']
            size_id = color_and_size_cleaned_data['size']

            size_instance = Size.objects.get(id=size_id).title
            color_instance = Color.objects.get(id=color_id).fa_name
            size_identification = Size.objects.get(id=size_id).id
            color_identification = Color.objects.get(id=color_id).id


            cart.add(product, price, color_instance, size_instance, color_identification, size_identification, inplace=inplace, quantity=quantity)
    return redirect('cart_detail')

def cart_clear(request):
    cart = Cart(request)

    if len(cart):
        cart.clear()
        messages.info(request, 'your cart is cleared from the product.')
    else:
        messages.info(request, 'your cart has not any product')

    return redirect('product_list')


def cart_remove(request, pk, product_version_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=pk)
    product_version_id = str(product_version_id)

    # print(Fore.RED + 'Product ID to Remove:', product.id)
    # print(Fore.BLUE + 'Product Version ID to Remove:', product_version_id)

    cart.cart_remove_product(product, product_version_id)

    # Display updated cart information
    # for item in cart:
        # print(Fore.GREEN + 'Product ID in Cart:', item['product_id'])
        # print(Fore.YELLOW + 'Product Version ID in Cart:', item['product_version_id'])
        # print(Fore.CYAN + 'Quantity in Cart:', item['quantity'])

    return redirect('cart_detail')

class CommentCreateView(CreateView):
    model = ProductComment
    form_class = CommentForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        product_id = int(self.kwargs['pk'])
        product = get_object_or_404(Product, id=product_id)
        obj.product = product
        return super().form_valid(form)


@login_required
def order_create_view(request):
    order_form = OrderForm()
    cart = Cart(request)

    if len(cart) == 0:
        messages.warning(request, 'your cart is empty from the product, please first choice some product.')
        return redirect('product_list')

    if request.method == 'POST':
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            order_obj = order_form.save(commit=False)
            order_obj.customer = request.user
            order_obj.save()

            for item in cart:
                OrderItem.objects.create(
                    order=order_obj,
                    product=item['product_obj'],
                    quantity=item['quantity'],
                    price=item['product_price'],
                )

            cart.clear()

            request.user.first_name = order_obj.first_name
            request.user.last_name = order_obj.last_name
            request.user.save()

            request.session['order_id'] = order_obj.id
            return redirect('payment_process')

    return render(request, 'store/order_create.html', context={'order_form': order_form, 'cart': cart})


def payment_process(request):
    order_id = request.session.get('order_id')

    order_obj = get_object_or_404(Order, id=order_id)


    toman_total_price = order_obj.get_total_price()
    rial_total_price = toman_total_price * 10


    zarinpal_request_url = 'https://api.zarinpal.com/pg/v4/payment/request.json'

    request_header={
        "accept":"application/json",
        "content-type":"application/json"
    }

    request_data={
        'merchant_id': settings.DJANGO_ZARINPAL_MERCHANT_ID,
        'amount':rial_total_price,
        'description': f'#{order_obj.id} : {order_obj.customer.first_name} {order_obj.customer.last_name}',
        'callback_url': request.build_absolute_uri(reverse('payment_callback'))
    }

    res = requests.post(url=zarinpal_request_url, data=json.dumps(request_data), headers=request_header)

store/templates/store/cart_detail.html
{% extends '_base.html' %}
{% load persian_translation_tags %}
{% load humanize %}


{% block page_title %}
    cart page
{% endblock %}

{% block content %}
    <!-- breadcrumb area start -->
    <div class="page-layout" data-background="assets/img/slider/shop.jpg">
        <div class="container">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                    <div class="breadcrumb-area text-center">
                        <h2 class="page-title">Cart</h2>
                        <div class="breadcrumb-menu">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb justify-content-center">
                                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                    <li class="breadcrumb-item"><a href="cart.html">cart</a></li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb area end -->

    <div class="f_cart_area pt-110 mb-100">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 col-lg-8 col-md-12">
                    <div class="cart_table">
                        <table>
                        {% if not cart.is_empty %}
                            <tr>
                                <td>Product</td>
                                <td>Title</td>
                                <td>price</td>
                                <td>Quantity</td>
                                <td>Size</td>
                                <td>Color</td>
                                <td>Total</td>

                            </tr>
                            {% for product in cart %}
                                <tbody>
                                <tr class="max-width-set">
                                    <td>
                                        <img src="{{ product.product_obj.thumbnail.url }}" alt="">
                                    </td>
                                    <td>{{ product.product_obj.fa_name }}</td>
                                    <td>${{ product.product_price }}</td>
                                    <td>
                                        <form method="POST" action="{% url 'cart_add' product.product_id %}">
                                            {% csrf_token %}
                                            <div class="viewcontent__action single_action pt-30">
                                                    <span>
                                                            <div class="quantity">
                                                                <input type="number"
                                                                       class="quantity-input"
                                                                       name="quantity"
                                                                       id="qty-1"
                                                                       value="{{ product.quantity }}"
                                                                       min="1"
                                                                >
                                                                <input type="hidden" name="inplace" value="True"
                                                                       id="id_inplace">
                                                                <input type="hidden" name="color"
                                                                       value="{{ product.color_id }}" id="color_id">
                                                                <input type="hidden" name="size"
                                                                       value="{{ product.size_id }}" id="size_id">

                                                            </div>
                                                        </span>
                                            </div>
                                            <button type="submit">update</button>
                                        </form>
                                    </td>
                                    <td>{{ product.size }}</td>
                                    <td>{{ product.color }}</td>

                                    <td>
                                        ${{ product.get_total_price_single_product }}
                                    </td>
                                    <td class="width-set">
                                        <a href="{% url 'cart_remove' pk=product.product_id product_version_id=product.product_version_id %}"><i
                                                class="fal fa-times-circle"></i></a>
                                    </td>
                                </tr>
                                </tbody>
                            {% endfor %}
                            <tfoot>
                            <tr class="design-footer">

                            <td colspan="1"><a class="text-info" href="{% url 'cart_clear' %}">clear cart</a></td>
                            </tr>
                            </tfoot>
                        {% else %}
                            <h3 class="text-warning" >your cart is empty please select some product in store... <store class="h2"><a class="text-info" href="{% url 'product_list' %}">go to Shop</a></store></h3>
                        {% endif %}

                        </table>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-4 col-md-12">
                    <div class="cart__acount">
                        <h5>Cart totals</h5>
                        <table>
                            <tr class="first-child lastchild">
                                <td>Shipping</td>
                                <td>Enter your address to view shipping options <br>
                                    Calculate shipping
                                </td>
                            </tr>
                            <tr class="first-child">
                                <td>Total</td>
                                <td>{{ cart.get_total_price|intcomma:False|translate_number }}</td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <a href="{% url 'order_create' %}"><input type="submit" value="procced to checkout"></a>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

store/templates/store/category_list.html
{% extends '_base.html' %}

{% block page_title %}
category list
{% endblock %}

{% block content %}
    <h1>category list page</h1>
{% endblock %}

store/templates/store/home.html
{% extends '_base.html' %}

{% block page_title %}
home page
{% endblock %}

{% block content %}
home page
{% endblock %}

store/templates/store/order_create.html
{% extends '_base.html' %}
{% load i18n %}
{% load persian_translation_tags %}
{% load humanize %}


{% block page_title %}
    order page
{% endblock %}


{% block content %}


    <div class="checkout_area pt-80">
        <div class="container">
            <div class="notification__message">
                <p><i class="fal fa-window-maximize"></i>Returning customer? Click here to <a
                        href="{% url 'account_login' %}">login</a></p>
            </div>
            <div class="row">
                <div class="col-xl-7 col-lg-7 col-md-12">
                    <div class="checkout_form mb-100">
                        <form action="" method="POST">
                            {% csrf_token %}
                            <div class="row mb-30">
                                <div class="col-xl-6 col-lg-6 col-md-6">
                                    <div class="checkout__wrap">
                                        <label>First name <span>*</span></label>
                                        <input type="text" name="{{ order_form.first_name.name }}">
                                        <div> {% if order_form.errors %}
                                            {% for message in order_form.first_name.errors %}
                                                <div class="alert alert-danger" role="alert">
                                                    {{ message }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6">
                                    <div class="checkout__wrap">
                                        <label>Last name <span>*</span></label>
                                        <input type="text" name="{{ order_form.last_name.name }}">
                                        <div> {% if order_form.errors %}
                                            {% for message in order_form.last_name.errors %}
                                                <div class="alert alert-danger" role="alert">
                                                    {{ message }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="checkout__wrap">
                                <label>Full address <span>*</span></label>
                                <input class="mb-20" type="text" name="{{ order_form.address.name }}"
                                       placeholder="house number and street number">
                                <div> {% if order_form.errors %}
                                    {% for message in order_form.address.errors %}
                                        <div class="alert alert-danger" role="alert">
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                                </div>
                            </div>
                            <div class="checkout__wrap">
                                <label>Postcode<span>*</span></label>
                                <input type="text" name="{{ order_form.post_code.name }}">
                                <div> {% if order_form.errors %}
                                    {% for message in order_form.post_code.errors %}
                                        <div class="alert alert-danger" role="alert">
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                                </div>
                            </div>
                            <div class="checkout__wrap">
                                <label>Phone <span>*</span></label>
                                <input type="text" name="{{ order_form.phone_number.name }}">
                                <div> {% if order_form.errors %}
                                    {% for message in order_form.phone_number.errors %}
                                        <div class="alert alert-danger" role="alert">
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                                </div>
                            </div>
                            <div class="checkout__wrap">
                                <label>Email address <span>*</span></label>
                                <input type="email" name="{{ order_form.email.name }}">
                                <div> {% if order_form.errors %}
                                    {% for message in order_form.email.errors %}
                                        <div class="alert alert-danger" role="alert">
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                                </div>
                            </div>
                            <div class="checkout__wrap">
                                <label>Order notes (optional) <span></span></label>
                                <textarea name="{{ order_form.order_note.name }}"
                                          placeholder="Note about your order, e.g special note for delivery"></textarea>
                                <div> {% if order_form.errors %}
                                    {% for message in order_form.order_note.errors %}
                                        <div class="alert alert-danger" role="alert">
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                                </div>
                            </div>
{#                            <button type="submit">{% trans 'go to payment' %}</button>#}
                        <div class="order-button">
                                <button type="submit">{% trans 'go to payment' %}</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-xl-5 col-lg-5 col-md-12">
                    <div class="cart__acount ml-50">
                        <h5>Your order</h5>
                        <table>
                        <tr class="first-child-2">
                            <td>name</td>
                            <td>quantity</td>
                            <td>total</td>
                        </tr>
                            {% for item in cart %}
                                <tr class="first-child-2">

                                    <td>{{ item.product_obj.fa_name }} </td>
                                    <td><span
                                            class="text-info"> {{ item.quantity }}</span> </td>
                                    <td>{{ item.get_total_price_single_product }} </td>
                                </tr>
                            {% endfor %}


                            <tr class="first-child-2">
                                <td>Total</td>
                                <td><span
                                            class="text-info">{{ cart.cart_all_quantity_length }}</span></td>
                                <td class="lightbluee">{% trans '$' %} {{ cart.get_total_price|intcomma:False|translate_number }}</td>
                            </tr>
                        </table>
                        <div class="checkout__accordion mt-30">
                            <div class="accordion" id="accordionExample">
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="headingOne">
                                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                                data-bs-target="#collapseOne" aria-expanded="true"
                                                aria-controls="collapseOne">
                                            {% trans 'Check payments' %}
                                        </button>
                                    </h2>
                                    <div id="collapseOne" class="accordion-collapse collapse show"
                                         aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            <p>پرداخت از درگاه زرین پال</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}